/**
 * Validates that the TS-side `generateHarmony` produces byte-identical
 * hex output to the Go-side `internal/harmony.Generate`. The fixture
 * is generated by `internal/harmony/fixture_gen_test.go` (gated by
 * HUETENSION_GEN_PARITY=1) and committed at
 * `web/src/composables/__fixtures__/harmony.json`.
 *
 * Run:
 *
 *   cd web && bun run scripts/check-parity.ts
 *
 * Exits non-zero on any drift. Wired into vitest in S10 — until then
 * this script is the safety net the advisor flagged for S5a.
 */

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  fromHex,
  toHex,
  generateHarmony,
  type HarmonyType,
} from '../src/composables/useColor';

interface Case {
  type: string;
  base: string;
  count: number;
  step?: number;
  result: string[];
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = resolve(__dirname, '../src/composables/__fixtures__/harmony.json');

const cases = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Case[];

let pass = 0;
let fail = 0;
const failures: string[] = [];

for (const c of cases) {
  const base = fromHex(c.base);
  const palette = generateHarmony(c.type as HarmonyType, base, {
    count: c.count,
    step: c.step,
  });
  const got = palette.map(toHex);
  const ok =
    got.length === c.result.length &&
    got.every((h, i) => h.toLowerCase() === c.result[i]?.toLowerCase());
  if (ok) {
    pass++;
  } else {
    fail++;
    failures.push(
      `  ${c.type}/${c.base}/${c.count}: want ${JSON.stringify(c.result)}, got ${JSON.stringify(got)}`,
    );
  }
}

console.log(`harmony parity: ${pass} pass, ${fail} fail (${cases.length} total)`);
if (fail > 0) {
  console.error('failures:');
  for (const f of failures) console.error(f);
  process.exit(1);
}
