// Package webdist exposes the built Vue SPA as an embed.FS used by the
// internal HTTP server (internal/web) to serve the UI from the binary.
//
// The dist/ subdirectory is generated by `bun run build` in later phases
// (Phase 3 S4+). For S1 it holds a placeholder index.html so the embed
// directive compiles on a fresh checkout — without that stub the binary
// won't build via `go install`.
//
// Phase 4 owns the CI gate that keeps dist/ in sync with src/.
package webdist

import "embed"

// Assets holds the built SPA. The `all:` prefix includes files whose
// names start with `.` or `_` (Vite emits `_vite/` chunks under hashed
// names; future PWA configs ship `.well-known/` entries).
//
//go:embed all:dist
var Assets embed.FS
